### ISSUE TITLE
No moduli smaller than 2048 bits

### ISSUE THREAD

**Issue by jpgoldberg** [sassman/srp6-rs#1]
Your current implementation includes moduli of 256, 512, and 1024 bits. These are unsafe. The first two are extraordinarily easy to break. If you really want to keep them because they are listed in ancient standards documents then hide them behind a feature and label them as never to be used in real systems.

**Comment by sassman** [comment]
Thanks for the feedback. 

There is already a feature flag for the legacy version, so it would make sense to hide the old and unsafe moduli behind as well.

**Comment by sassman** [comment]
closed by #4

**Comment by sassman** [comment]
@jpgoldberg the changes are released as version [1.0.0-alpha.2](https://crates.io/crates/srp6), also the docs are now complete and should be polished.
