### ISSUE TITLE
Do not suggest that RSA moduli are usable 

### ISSUE THREAD

**Issue by jpgoldberg** [sassman/srp6-rs#2]
In the docs in `defaults.rs` you have the text

```
**NOTE:** if you need to roll your own modulus, you can generate one e.g. like this:
\```sh
openssl genrsa 1024 | openssl rsa -modulus
\```
```

An RSA modulus cannot be used as an SRP group modulus. An RSA modulus is a composite number, and SRP group modulus must be a safe prime. (Also 1024 is _way_ too small. See issue #1 )

**Comment by sassman** [comment]
Thanks for your suggestions @jpgoldberg 
In version `v1.0.0-beta.1` there is now more strong emphasis in the docs that < 2048 should not be used.
